# Generated by Django 5.0.4 on 2024-08-04 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0002_usercomment_delete_lowpoint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserComment',
            new_name='LowPoint',
        ),
    ]
